#!/bin/bash

sleep 3

source /opt/ros/kinetic/setup.bash

roscore &

sleep 3 && roslaunch sbg_driver sbg_ellipseA.launch &

sleep 3 && roslaunch velodyne_pointcloud VLP16_points.launch &

# rosbag record -a &
# rosnode list &
# rosnode kill /record_#
