#!/bin/bash

roscore &

sleep 2 && roslaunch sbg_driver sbg_ellipseA.launch &

sleep 2 && source $HOME/catkin_vlp/devel/setup.bash && roslaunch velodyne_pointcloud VLP16_points.launch &

# rosbag record -a &
# rosnode list &
# rosnode kill /record_#
